---
- name: Configure hostname | runtime
  hostname:
    name: "{{ var_host_name }}"

- name: Configure hostname | config
  template:
    src: templates/hostname.j2
    dest: /etc/hostname

- name: Configure hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Disable SELinux | config
  selinux:
    state: disabled

- name: Disable SELinux | runtime
  shell:
    cmd: "selinuxenabled && setenforce 0 || true"

- name: Install yum repo
  yum:
    name: epel-release
    state: present

- name: Install yum pkgs
  yum:
    name: "{{ yum_pkg }}"
    state: present
    update_cache: yes
  tags:
    - install_pkgs
    - never

- name: Conf bash_hist
  copy:
    src: files/bash_hist.sh
    dest: /etc/profile.d
    mode: u+rx

- name: Conf sshd_conf
  copy:
    src: files/sshd_conf
    dest: /etc/ssh
  notify:
    - sshd_restart

- name: Conf screenrc
  copy:
    src: files/screenrc
    dest: /etc/screenrc

- name: Disable unneccessory services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - firewalld
    - NetworkManager
    - NetworkManager-dispatcher
    - NetworkManager-wait-online
