---
- name: Configure hostname | runtime
  hostname:
    name: "{{ var_host_name }}"

- name: Configure hostname | config
  template:
    src: templates/hostname.j2
    dest: /etc/hostname

- name: Configure hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Disable SELinux | config
  selinux:
    state: disabled

- name: Disable SELinux | runtime
  shell:
    cmd: "selinuxenabled && setenforce 0 || true"

- name: Install yum repo
  yum:
    name: epel-release
    state: present

- name: Install RDO repo
  yum:
    name: https://www.rdoproject.org/repos/rdo-release.rpm
    state: present

- name: Install yum pkgs
  yum:
    name: "{{ yum_pkg }}"
    state: present
    update_cache: yes
  tags:
    - install_pkgs
    # - never

- name: Install PackStack
  yum:
    name: openstack-packstack
    state: present

- name: Enable and start chronyd
  systemd:
    name: chronyd
    enabled: yes
    state: started

- name: Enable and start rabbitmq
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Conf bash_hist
  copy:
    src: files/bash_hist.sh
    dest: /etc/profile.d
    mode: u+rx

- name: Conf sshd_conf
  copy:
    src: files/sshd_conf
    dest: /etc/ssh
  notify:
    - sshd_restart

- name: Conf screenrc
  copy:
    src: files/screenrc
    dest: /etc/screenrc

- name: Disable unneccessory services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - firewalld
    - NetworkManager
    - NetworkManager-dispatcher
    - NetworkManager-wait-online

### Install openstack from source - BEGIN
#
- name: Clone repository of DevStack
  git:
    repo: https://github.com/openstack-dev/devstack.git
    dest: /opt/devstack
    version: stable/queens
  ignore_errors: yes

- name: Transfer stackrc
  template:
    src: templates/stackrc.j2
    dest: /opt/devstack/stackrc

- name: Create user stack | chmod create-stack-user.sh
  file:
    path: /opt/devstack/tools/create-stack-user.sh
    mode: u+x

- name: Create user stack | run create-stack-user.sh
  shell:
    cmd: /opt/devstack/tools/create-stack-user.sh

- name: Transfer local.conf
  template:
    src: templates/local.conf.j2
    dest: /opt/devstack/local.conf

- name: Create user stack | chmod /opt/devstack
  file:
    path: /opt/devstack
    state: directory
    owner: stack
    group: stack
    recurse: yes
  # tags:
  #   - install_openstack

#
### Install openstack from source - END
